- name: bsdinstall template script
  copy:
    dest: "{{ jail.root.mountpoint }}/.template/{{ jailname }}"
    mode: 0644
    content: |
      DISTRIBUTIONS="base.txz"
      export nonInteractive="YES"
      #!/bin/sh
      IGNORE_OSVERSION=yes pkg install -y {{ jail.python | default('python') }}
      sysrc sshd_enable="YES"
      {% for network in jailcfg.inet | jail_net_conf(jailname) %}
      sysrc ifconfig_{{ network.ifname }}="{{ network.ifconf }}"
      {% endfor %}
      sysrc defaultrouter={{ jailcfg.defaultrouter }}
      {% set juser = hostvars[jailname].get('ansible_user', jail.user) %}
      {% set juid  = hostvars[jailname].get('ansible_user_uid','') %}
      {% set jgecos = hostvars[jailname].get('ansible_user_gecos','') %}
      echo "{{ juser }}:{{ juid }}:::::{{ jgecos }}:::" | adduser -w no -f -
      pkg install -y sudo
      echo "{{ juser }} ALL=(ALL) NOPASSWD: ALL" >/usr/local/etc/sudoers.d/{{ juser }}
      install -d -m 700 /home/{{ juser }}/.ssh
      echo "{{ jail.ssh_key }}" >/home/{{ juser }}/.ssh/authorized_keys
      chown -R {{ juser }}:{{ juser }} /home/{{ juser }}/.ssh

- name: bsdinstall jails # noqa command-instead-of-shell
  # You can't pass environemtn variables using the command module
  shell: bsdinstall jail "{{ jail.root.mountpoint }}/{{ jailname }}"
  environment:
    SCRIPT: "{{ jail.root.mountpoint }}/.template/{{ jailname }}"
    BSDINSTALL_DISTSITE: "{{ jail.mirror | default('http://ftp.freebsd.org/') | trim('/') }}/pub/FreeBSD/releases/{{ ansible_machine }}/{{ ansible_architecture }}/{{ ansible_distribution_release | regex_replace('-p\\d+$', '') }}" # noqa yaml[line-length]
  args:
    creates: "{{ jail.root.mountpoint }}/{{ jailname }}/bin"

- name: setup network when jail is already running
  community.general.sysrc:
    # jail: parameter works only, if the jail is running. This way, it's 100% sure, the change happens
    path: "{{ jail.root.mountpoint }}/{{ jailname }}/etc/rc.conf"
    name: "ifconfig_{{ item.ifname }}"
    value: "{{ item.ifconf }}"
    state: present
  loop: "{{ jailcfg.inet | jail_net_conf(jailname) }}"
