- name: Install debootstrap if neccesary
  ansible.builtin.package:
    name:
      - debootstrap
    state: present

- name: Run first stage of debootstrap
  ansible.builtin.command: "debootstrap --foreign --no-merged-usr --exclude=usr-is-merged --arch={{ ansible_architecture }} {{ jailcfg.osver | default('ascii') }} {{ jail.root.mountpoint }}/{{ jailname }} {{ jailcfg.mirror | default('http://deb.devuan.org/merged/') }} {{ script_version_overrides[jailcfg.osver | default('default')] }}" # noqa yaml[line-length]
  args:
    creates: "{{ jail.root.mountpoint }}/{{ jailname }}/etc"

- name: Check if still need the second stage
  ansible.builtin.stat:
    path: "{{ jail.root.mountpoint }}/{{ jailname }}/debootstrap"
  register: debootstrap_stat

- name: Check if second stage is actually over and should skip on third stage
  ansible.builtin.stat:
    path: "{{ jail.root.mountpoint }}/{{ jailname }}/debootstrap/third_stage"
  register: dbs_third
  when: debootstrap_stat.stat.isdir is defined and debootstrap_stat.stat.isdir

- name: Patch debootstrap for second stage
  ansible.builtin.command: "ed {{ jail.root.mountpoint }}/{{ jailname }}/debootstrap/debootstrap"
  args:
    stdin: |
      /TARGET" = "\/"
      i
      HOST_OS="freebsd"
      HOST_ARCH="{{ ansible_architecture }}"

      .
      w
    stdin_add_newline: true
  register:
    patch_debootstrap
  when: debootstrap_stat.stat.isdir is defined and debootstrap_stat.stat.isdir and not dbs_third.stat.exists
  changed_when: patch_debootstrap.rc == 0

- name: Create /usr/local/bin
  ansible.builtin.file:
    path: "{{ jail.root.mountpoint }}/{{ jailname }}/usr/local/bin"
    mode: '0755'
    state: directory

- name: Create bash symlink for debootstrap second stage
  ansible.builtin.file:
    src: /bin/bash
    dest: "{{ jail.root.mountpoint }}/{{ jailname }}/usr/local/bin/bash"
    state: link
    force: true
  when: debootstrap_stat.stat.isdir is defined and debootstrap_stat.stat.isdir

- name: Create grep symlink for debootstrap second stage
  ansible.builtin.file:
    src: /bin/grep
    dest: "{{ jail.root.mountpoint }}/{{ jailname }}/usr/local/bin/grep"
    state: link
    force: true
  when: debootstrap_stat.stat.isdir is defined and debootstrap_stat.stat.isdir

- name: Mount linprocfs
  ansible.posix.mount:
    path: "{{ jail.root.mountpoint }}/{{ jailname }}/proc"
    src: linprocfs
    fstype: linprocfs
    opts: rw,late
    fstab: "/etc/fstab.{{ jailname }}"
    state: mounted
  when: debootstrap_stat.stat.isdir is defined and debootstrap_stat.stat.isdir

- name: Mount linsysfs
  ansible.posix.mount:
    path: "{{ jail.root.mountpoint }}/{{ jailname }}/sys"
    src: linsysfs
    fstype: linsysfs
    opts: rw,late
    fstab: "/etc/fstab.{{ jailname }}"
    state: mounted
  when: debootstrap_stat.stat.isdir is defined and debootstrap_stat.stat.isdir

- name: Mount tmpfs
  ansible.posix.mount:
    path: "{{ jail.root.mountpoint }}/{{ jailname }}/tmp"
    src: tmpfs
    fstype: tmpfs
    opts: rw,late,mode=1777
    fstab: "/etc/fstab.{{ jailname }}"
    state: mounted
  when: debootstrap_stat.stat.isdir is defined and debootstrap_stat.stat.isdir

- name: Run second stage
  ansible.builtin.command: "chroot {{ jail.root.mountpoint }}/{{ jailname }} /debootstrap/debootstrap --second-stage"
  register: second_stage
  when: debootstrap_stat.stat.isdir is defined and debootstrap_stat.stat.isdir and not dbs_third.stat.exists
  failed_when: false
  changed_when: second_stage.rc == 0

- name: Copy systems resolv.conf for this stage
  ansible.builtin.copy:
    src: /etc/resolv.conf
    dest: "{{ jail.root.mountpoint }}/{{ jailname }}/etc/resolv.conf"
    mode: '0644'
    remote_src: true
  when: debootstrap_stat.stat.isdir is defined and debootstrap_stat.stat.isdir

- name: Raise apt limits
  ansible.builtin.copy:
    dest: "{{ jail.root.mountpoint }}/{{ jailname }}/etc/apt/apt.conf.d/20archive"
    mode: '0644'
    content: |
      APT::Cache-Limit "100000000";
      APT::Cache-Start "100000000";

- name: Prepare a third stage
  ansible.builtin.copy:
    dest: "{{ jail.root.mountpoint }}/{{ jailname }}/debootstrap/third_stage"
    mode: '0755'
    owner: root
    group: wheel
    content: |
      #!/bin/bash
      exec >>/debootstrap/third_stage.log 2>&1
      dpkg -l || cp /var/lib/dpkg/status-old /var/lib/dpkg/status
      dpkg --configure --pending
      if !  dpkg -i /var/cache/apt/archives/*.deb ; then
        dpkg --configure --pending
        dpkg -i /var/cache/apt/archives/init_*.deb
      fi
      apt update
      apt install -y syslog-ng-core ed
      cat <<END | ed /etc/syslog-ng/syslog-ng.conf
      /system
      s/^/#/
      /internal
      i
      unix-stream("/var/lib/misc/log");
      .
      w
      END
      dpkg --purge rsyslog
      dpkg --configure --pending
      apt install -y ssh
      ln -s ../init.d/networking /etc/rc3.d/S01networking
      update-rc.d networking enable
      {% set juser = hostvars[jailname].get('ansible_user', jail.user) %}
      {% set jgecos = hostvars[jailname].get('ansible_user_gecos', '') %}
      adduser --disabled-password --gecos "{{ jgecos }}" {{ juser }}
      apt install sudo
      echo "{{ juser }} ALL=(ALL) NOPASSWD: ALL" >/etc/sudoers.d/{{ juser }}
      install -d -m 700 /home/{{ juser }}/.ssh
      echo "{{ jail.ssh_key }}" >/home/{{ juser }}/.ssh/authorized_keys
      chown -R {{ juser }}:{{ juser }} /home/{{ juser }}/.ssh
      mv /debootstrap /var/log/debootstrap
  when: debootstrap_stat.stat.isdir is defined and debootstrap_stat.stat.isdir

- name: Setup jail loopback network interface
  ansible.builtin.blockinfile:
    path: "{{ jail.root.mountpoint }}/{{ jailname }}/etc/network/interfaces"
    mode: '0644'
    create: true
    marker: "# {mark} ANSIBLE MANAGED: lo0"
    block: |
      auto lo0
      iface lo0 inet manual
        up /native/bin/ifconfig lo0 inet 127.0.0.1 netmask 255.0.0.0
        down /native/bin/ifconfig lo0 down

- name: Setup jails network interfaces config
  ansible.builtin.blockinfile:
    path: "{{ jail.root.mountpoint }}/{{ jailname }}/etc/network/interfaces"
    mode: '0644'
    create: true
    marker: "# {mark} ANSIBLE MANAGED: {{ item.ifname }}"
    block: |
      auto {{ item.ifname }}
      iface {{ item.ifname }} inet manual
        up /native/bin/ifconfig {{ item.ifname }} {{ item.ifconf }}
      {% if ansible_loop.first %}
        up /native/bin/route add default {{ jailcfg.defaultrouter }}
      {% endif %}
        down /native/bin/ifconfig {{ item.ifname }} down
  with_items: "{{ jailcfg.inet | jail_net_conf(jailname) }}"
  loop_control:
    extended: true

- name: Run third stage
  ansible.builtin.command: "chroot {{ jail.root.mountpoint }}/{{ jailname }} /debootstrap/third_stage"
  register: third_stage
  when: debootstrap_stat.stat.isdir is defined and debootstrap_stat.stat.isdir
  changed_when: true

- name: Clean up bash symlink
  ansible.builtin.file:
    dest: "{{ jail.root.mountpoint }}/{{ jailname }}/usr/local/bin/bash"
    state: absent
  when: second_stage is defined or debootstrap_stat.stat.isdir is not defined

- name: Clean up grep symlink
  ansible.builtin.file:
    dest: "{{ jail.root.mountpoint }}/{{ jailname }}/usr/local/bin/grep"
    state: absent
  when: second_stage is defined or debootstrap_stat.stat.isdir is not defined

- name: Copy native binaries in order to be able to start network on boot
  ansible.builtin.command: "/usr/local/sbin/linjailsetup {{ jail.root.mountpoint }} {{ jailname }}"
  args:
    creates: "{{ jail.root.mountpoint }}/{{ jailname }}/native"
